#!/bin/sh

# == Debian
# written by Rene K. Mueller <spiritdude@gmail.com>
#    installs debian, release name as argument (no number)

DIR=$1
ID=`basename $1`

if [ -n "$2" ] 
then
   DIST=$2
else
   DIST=sid
fi

echo "\tfetching debian ${DIST}";

debootstrap ${DIST} ${DIR}

# -- set hostname
mkdir -p ${DIR}/etc; echo "${ID}" > ${DIR}/etc/hostname
#chroot ${DIR} /bin/sh -c "/bin/hostname ${ID}"

echo "rootfs / rootfs rw 0 0" > ${DIR}/etc/mtab

