#!/bin/sh

# == Debian
# written by Rene K. Mueller <spiritdude@gmail.com>
#    installs debian, release name as argument

DIR=$1
ID=`basename $1`
NUM=$2
DIST=sid

if [ -n "${NUM}" ] 
then
   DIST=${NUM}
fi

echo "\tfetching debian ${DIST}";

debootstrap ${DIST} ${DIR}

# -- set hostname
mkdir -p ${DIR}/etc; echo "${ID}" > ${DIR}/etc/hostname
#chroot ${DIR} /bin/sh -c "/bin/hostname ${ID}"

echo "rootfs / rootfs rw 0 0" > ${DIR}/etc/mtab

