#!/bin/sh

# == OpenSUSE
# written by Rene K. Mueller <spiritdude@gmail.com>
#    installs opensues-12.1 using rinse

ID=`basename $1`
rinse --arch amd64 --directory $1 --distribution opensuse-12.1

# -- set hostname
mkdir -p $1/etc; echo "${ID}" > $1/etc/hostname
#chroot $1 /bin/sh -c "/bin/hostname ${ID}"

echo "rootfs / rootfs rw 0 0" > $1/etc/mtab

